plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ryusgua.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ryusgua.app'
        minSdk 23
        targetSdk 35
        versionCode 100
        versionName '1.0.0'
    }

    flavorDimensions 'compat'
    productFlavors {
        standard {
            dimension 'compat'
            minSdk 26
        }
        legacy {
            dimension 'compat'
            minSdk 23
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

def hasReleaseSigning = [
        "ZG_STORE_FILE",
        "ZG_STORE_PASSWORD",
        "ZG_KEY_ALIAS",
        "ZG_KEY_PASSWORD"
].every { project.hasProperty(it) }

if (hasReleaseSigning) {
    android {
        signingConfigs {
            release {
                storeFile file(project.property("ZG_STORE_FILE"))
                storePassword project.property("ZG_STORE_PASSWORD")
                keyAlias project.property("ZG_KEY_ALIAS")
                keyPassword project.property("ZG_KEY_PASSWORD")
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
            }
        }
    }
}
